### ISSUE TITLE
Decide on Use Case Diagram Software

### ISSUE THREAD

**Issue by mattlyons0** [mattlyons0/DiceGame#2]
Decide how we want to create a use case diagram. What did you guys use for that assignment.

I used [Draw.io](http://draw.io). Its not super great, but not awful. Basically a rich editor to draw lines and stuff which can create a pdf we can put in the repo.

**Comment by Jambo-Bwana** [comment]
Admittedly, I used Word (not recommended). Full points, so nbd.

I'm cool with using whatever 1) looks nice and 2) is user-friendly

**Comment by mattlyons0** [comment]
https://www.lucidchart.com
